// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWqHqdIytRkJHdjQymYKtFzomnugDTIMc',
    appId: '1:310702274447:web:856f7bc4f63feba3163dfa',
    messagingSenderId: '310702274447',
    projectId: 'pingolearn-f09b7',
    authDomain: 'pingolearn-f09b7.firebaseapp.com',
    storageBucket: 'pingolearn-f09b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsfuS_018r6s-Flc9hZxuIReFf1fgPvVE',
    appId: '1:310702274447:android:e44637ee763afc9b163dfa',
    messagingSenderId: '310702274447',
    projectId: 'pingolearn-f09b7',
    storageBucket: 'pingolearn-f09b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVqH0PdMSsuyqNHpYcIOJkcGcvPZLUn1E',
    appId: '1:310702274447:ios:8c2501dfcce80475163dfa',
    messagingSenderId: '310702274447',
    projectId: 'pingolearn-f09b7',
    storageBucket: 'pingolearn-f09b7.appspot.com',
    iosClientId: '310702274447-gtm7sgu3qci91cs3gfs5sp1sqv05hkhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVqH0PdMSsuyqNHpYcIOJkcGcvPZLUn1E',
    appId: '1:310702274447:ios:8c2501dfcce80475163dfa',
    messagingSenderId: '310702274447',
    projectId: 'pingolearn-f09b7',
    storageBucket: 'pingolearn-f09b7.appspot.com',
    iosClientId: '310702274447-gtm7sgu3qci91cs3gfs5sp1sqv05hkhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingolearn',
  );
}
